apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: microservices
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  # ClusterIP: solo accesible desde dentro del cluster, nunca expuesto al exterior
  type: ClusterIP
