apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: microservices
spec:
  selector:
    app: products-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
